# Generated by Django 4.2.7 on 2023-11-06 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_mylistings"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listing",
            old_name="zipcode",
            new_name="zipcode1",
        ),
    ]
