# Generated by Django 4.2.7 on 2023-11-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_rename_zipcode_listing_zipcode1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="bathrooms",
            field=models.IntegerField(),
        ),
    ]
